Dev header
VSerj/i-studio pull request #3
Opened 2020-10-18 21:37 UTC by VSerj

I want to merge dev-header with master.
But I also foolishly changed other code not related to this branch.
I apologize.

2020-10-18 23:03 UTC, bringmetheaugust reviewed
в модуле **stretch_header.js** вообще мало что понятно.
оставь комментарии в самых запутанных местах

2020-10-18 23:09 UTC, bringmetheaugust requested changes
переделай все, что в комментах ревью

2020-10-19 00:34 UTC, VSerj commented on src/js/menu_btn.js
> +})
спасибо за подсказку и за ссылку.

2020-10-19 00:44 UTC, VSerj commented on src/js/menu_btn.js
> +
ты прав, я исковеркал гайд по стилю [Стилизация](https://learn.javascript.ru/coding-style#sintaksis)

2020-10-19 00:45 UTC, VSerj commented on src/js/rollout_fade_effect.js
> +  let rollOutOptions = {
лет лет лет лет - неееет

2020-10-19 15:02 UTC, VSerj commented
- Удалили лишние пустые строки.
- Заменил let на const
- Удалили лишний декоратор 
- Применил деструктуризацию
- Избавился от лишних вложеностей для If
- Удалили пустой файл Js

2020-10-19 15:09 UTC, bringmetheaugust requested changes
чётко, кроме нотации комментариев. переделать это и можно в прод запускать

2020-10-19 15:09 UTC, bringmetheaugust commented on src/js/rollout_fade_effect.js
> +    entries.forEach((entry) => {
нет необходимости оборачивать один аргумент в скобки для стрелочных функций

2020-10-19 15:09 UTC, bringmetheaugust commented on src/js/stretch_header.js
> + * isHandlerStretch указывает на существование
комментарии об описании для переменных и функций/методов нужно писать над этими субстанциями или рядом с ними.
* если субстанция состоит из одной строки, то пишем коммент возле неё
`let isHandlerStretch = false // указывает на существование`

* если субстанция состоит из более, чем 2 строк кода, то пишем коммент сверху
```
// меняет высоту header`а добавляя STRETCH_SELECTOR в зависимости от уловий
function stretch() {
    (
      !header.classList.contains(STRETCH_SELECTOR) &&
      !window.scrollY && 
      !BREAKPOINT_SM_DESKTOP.matches
    )
    ? header.classList.add(STRETCH_SELECTOR)
    : header.classList.remove(STRETCH_SELECTOR)
  }
}


```

2020-10-19 16:28 UTC, VSerj commented
переделал комментарии и стрелку

2020-10-19 17:17 UTC, bringmetheaugust approved these changes
good job, boy!

2020-10-19 17:18 UTC, merged

2020-10-19 17:18 UTC, bringmetheaugust commented
замержил, уже в мастере